#pragma once
#include "SDK.hpp"   // adopted SDK drop - game::offsets is the source of truth
#include <cstddef>
#include <cstdint>

// GENERATED by tools/gen_offsets.py from the dumped SDK - do not hand-edit.
// Dump:    Steam AppID 1808500  buildid 25363021 |  2026-09-22 | image    0x13da8000  (module base 0x140000000) | v20260922
// Every constant below carries its source: <Class>.<Property> offsets come
// straight from the dump; slots marked DERIVED/lit have no reflecting property
// on this build and keep their probed value. [live] marks a value pinned
// against the running target because no dump carries it.
// [live] ComponentToWorld - ArcOffsets::SceneComponent::COMPONENT_TO_WORLD = 0x310 (v20260922 dumper + user); translation at +0x20 => 0x330
// [live] Health - ArcOffsets::HealthComponent::CURRENT_HEALTH = 0x6D0 (the 0x700 dump field is an FName shadow)
// [live] LastRenderTime - vis check user-provided 2026-09-23: PrimitiveComponent::LastRenderTime = 0x480 (plain float; drop's 0x4C0 reads zero now)
// [live] LastRenderTimeOnScreen - vis check user-provided 2026-09-23: LastRenderTimeOnScreen = 0x484 (plain float; was 0x4C4)
// [live] MaxHealth - ArcOffsets::HealthComponent::MAX_HEALTH = 0x348 (native, in the dump's Pad_0340 hole)

namespace Offsets {
    // -- SDK drop: every game::offsets value is mirrored here --------
    constexpr std::ptrdiff_t UWorld                                 = static_cast<std::ptrdiff_t>(game::offsets::GWORLD); // GWORLD - GWORLD global  [lit/probed]
    constexpr uint64_t       GNamePoolRva                           = static_cast<uint64_t>(game::offsets::GNAMES); // GNAMES - GNAMES pool global  [lit/probed]
    constexpr uint64_t       FNameKeyTableRva                       = static_cast<uint64_t>(game::offsets::KEYTABLE); // KEYTABLE - FName key table  [lit/probed]
    constexpr uint64_t       FStringVerificationRva                 = static_cast<uint64_t>(game::offsets::FString_Verification_Offset); // FString_Verification_Offset - FString verification data  [lit/probed]

    // -- Globals only the 20260922 dump carries ----------------------
    constexpr uint64_t       GObjectsRva                            = 0x10C56FE0;                                  // 0x10C56FE0 - OFFSET_GOBJECTS (Dumpspace OffsetsInfo / dump header)  [lit/probed]
    constexpr uint64_t       ProcessEventRva                        = 0x5AF560;                                    // 0x5AF560 - OFFSET_PROCESSEVENT  [lit/probed]
    constexpr uint32_t       ProcessEventIndex                      = 0x4C;                                        // 0x4C - INDEX_PROCESSEVENT  [lit/probed]

    // -- Reflection layout (FField/FProperty walkers) ----------------
    constexpr std::ptrdiff_t UStruct_SuperStruct                    = 0xB0;                                        // CoreUObject.Struct.SuperStruct = 0xB0 - UStruct::SuperStruct
    constexpr std::ptrdiff_t UStruct_PropertyLink                   = 0xB8;                                        // CoreUObject.Struct.Children = 0xB8 - UStruct::Children (the FField chain head)
    constexpr std::ptrdiff_t FProperty_PropertyLinkNext             = 0x98;                                        // CoreUObject.Field.Next = 0x98 - FField::Next
    constexpr std::ptrdiff_t FObjectPropertyBase_PropertyClass      = 0xE0;                                        // CoreUObject.ObjectPropertyBase.PropertyClass = 0xE0 - FObjectPropertyBase::PropertyClass
    constexpr std::ptrdiff_t FField_ClassPrivate                    = 0x60;                                        // 0x60 - FField::ClassPrivate (FField is not reflected - no dump source)  [lit/probed]
    constexpr std::ptrdiff_t FFieldClass_SuperClass                 = 0x40;                                        // 0x40 - FFieldClass::SuperClass (FFieldClass is not reflected - no dump source)  [lit/probed]

    // -- Not covered by the dump (project-local / non-reflected) -----
    constexpr uint64_t       GameStateGlobalRva                     = 0xDCA7C88;                                   // 0xDCA7C88 - UNVERIFIED: no GameState global in the 20260922 dump  [lit/probed]
    constexpr uint64_t       FNameKeystreamLegacyRva                = 0xE2997F4;                                   // 0xE2997F4 - legacy v818 keystream  [lit/probed]
    constexpr uint64_t       FNameBlockMaskRva                      = 0xB523C50;                                   // 0xB523C50 - legacy SSE block mask  [lit/probed]
    constexpr uint64_t       GUObjectArrayChunksRva                 = GObjectsRva;                                 // GObjectsRva - == GObjectsRva (old drop's name for the same global)  [lit/probed]
    constexpr uint64_t       GObjPshufbMaskRva                      = 0xAD97CC0;                                   // 0xAD97CC0 - 16-byte PSHUFB mask (data RVA - no dump source)  [lit/probed]
    constexpr uint64_t       FFieldNameKey0Rva                      = 0xE7B5330;                                   // 0xE7B5330 - FField name key (data RVA)  [lit/probed]
    constexpr uint64_t       FFieldNameKey1Rva                      = 0xE6F0554;                                   // 0xE6F0554 - FField name key (data RVA)  [lit/probed]
    constexpr uint64_t       GameInstanceXorKey0Rva                 = 0xB06C380;                                   // 0xB06C380 - GI pointer XOR key low  [lit/probed]
    constexpr uint64_t       GameInstanceXorKey1Rva                 = 0xB06C390;                                   // sdk/sdk.txt ArcOffsets::GameInstanceDecrypt::XOR_KEY_RVA_2 = 0xB06C390 - GI pointer XOR key high
    constexpr uint64_t       GameInstanceShuffleMaskRva             = 0xB09C350;                                   // 0xB09C350 - GI PSHUFB mask  [lit/probed]
    constexpr std::ptrdiff_t GameInstance_WorldBackRef              = 0x2F0;                                       // 0x2F0 - GI -> UWorld back-reference (non-UPROPERTY)  [lit/probed]
    constexpr uint64_t       PlayerNameSimdMaskRva                  = 0xAD2FC50;                                   // sdk/sdk.txt ArcOffsets::GetObjectIdCrypto::SIMD_MASK_RVA = 0xAD2FC50 - player-name PSHUFB mask

    // -- UObjectBase (engine-invariant layout) -----------------------
    constexpr std::ptrdiff_t UObject_ObjectFlags                    = 0x08;                                        // 0x08 - UObjectBase::ObjectFlags  [lit/probed]
    constexpr uint32_t       RF_BeginDestroyed                      = 0x00800000;                                  // 0x00800000 - EObjectFlags  [lit/probed]
    constexpr uint32_t       RF_FinishDestroyed                     = 0x01000000;                                  // 0x01000000 - EObjectFlags  [lit/probed]

    // -- UWorld ------------------------------------------------------
    constexpr std::ptrdiff_t PersistentLevel                        = 0x110;                                       // Engine.World.PersistentLevel = 0x110
    constexpr std::ptrdiff_t StreamingLevels                        = 0x170;                                       // Engine.World.StreamingLevels = 0x170
    constexpr std::ptrdiff_t Levels                                 = 0x2F0;                                       // Engine.World.Levels = 0x2F0
    constexpr std::ptrdiff_t OwningGameInstance                     = 0x478;                                       // sdk/sdk.txt ArcOffsets::UWorld::GAME_INSTANCE = 0x478 - SDK drop: encrypted UWorld::OwningGameInstance slot
    constexpr std::ptrdiff_t LevelCollections                       = 0x338;                                       // Engine.World.LevelCollections = 0x338 - TArray<FLevelCollection>
    constexpr std::ptrdiff_t AuthorityGameMode                      = 0x310;                                       // Engine.World.AuthorityGameMode = 0x310
    constexpr std::ptrdiff_t PhysicsField                           = 0x508;                                       // Engine.World.PhysicsField = 0x508
    constexpr std::ptrdiff_t LevelCollection_GameState              = 0x8;                                         // Engine.LevelCollection.GameState = 0x8 - FLevelCollection::GameState
    constexpr std::ptrdiff_t LevelCollection_PersistentLevel        = 0x20;                                        // Engine.LevelCollection.PersistentLevel = 0x20 - FLevelCollection::PersistentLevel
    constexpr std::ptrdiff_t LevelCollection_Stride                 = 0x78;                                        // sizeof(Engine.LevelCollection) from dump - FLevelCollection element stride
    constexpr std::ptrdiff_t GameState                              = LevelCollections;                            // LevelCollections - UWorld has no direct GameState field - use LevelCollections  [lit/probed]

    // -- GameInstance / LocalPlayer ----------------------------------
    constexpr std::ptrdiff_t LocalPlayers                           = 0x130;                                       // sdk/sdk.txt ArcOffsets::GameInstance::LOCAL_PLAYERS = 0x130 (drop re-checked 2026-09-22) - SDK drop: UGameInstance::LocalPlayers
    constexpr std::ptrdiff_t LocalPlayer_PlayerController           = 0xA0;                                        // Engine.Player.PlayerController = 0xA0 - ULocalPlayer inherits UPlayer
    constexpr std::ptrdiff_t LocalPlayer_ControllerId               = 0x270;                                       // Engine.LocalPlayer.ControllerId = 0x270

    // -- ULevel ------------------------------------------------------
    constexpr std::ptrdiff_t AActors                                = 0x110;                                       // 0x110 - ULevel::Actors TArray<AActor*> data ptr - Level_classes.hpp (non-UPROPERTY)  [lit/probed]
    constexpr std::ptrdiff_t ActorsCount                            = AActors + 0x8;                               // AActors + 0x8 - TArray num (ULevel::Actors + 0x8)  [lit/probed]
    constexpr std::ptrdiff_t Level_OwningWorld                      = 0x138;                                       // Engine.Level.OwningWorld = 0x138
    constexpr std::ptrdiff_t ActorCluster                           = 0x158;                                       // Engine.Level.ActorCluster = 0x158 - the live actor path on this build
    constexpr std::ptrdiff_t LevelActorContainer_Actors             = 0x98;                                        // Engine.ActorContainer.Actors = 0x98 - ULevelActorContainer::Actors
    constexpr std::ptrdiff_t LevelActorContainer_ActorCount         = LevelActorContainer_Actors + 0x8;            // LevelActorContainer_Actors + 0x8 - TArray num  [lit/probed]

    // -- GameState ---------------------------------------------------
    constexpr std::ptrdiff_t GameState_PlayerArray                  = 0x498;                                       // Engine.GameStateBase.PlayerArray = 0x498
    constexpr std::ptrdiff_t GameState_EnemyCount                   = 0xA00;                                       // Angelscript.PioneerGameState.EnemyCount = 0xA00 - was lit:0x0940 - the dump reflects it at 0xA00
    constexpr std::ptrdiff_t GameState_PickupCount                  = 0xA04;                                       // Angelscript.PioneerGameState.PickupCount = 0xA04
    constexpr std::ptrdiff_t GameState_GamePhase                    = 0x9D0;                                       // Angelscript.PioneerGameState.GamePhase = 0x9D0

    // -- GameViewportClient ------------------------------------------
    constexpr std::ptrdiff_t GameViewportClient_World               = 0x1C8;                                       // Engine.GameViewportClient.World = 0x1C8

    // -- Controller / PlayerController -------------------------------
    constexpr std::ptrdiff_t AcknowledgedPawn                       = 0x418;                                       // sdk/sdk.txt ArcOffsets::Controller::ACKNOWLEDGED_PAWN = 0x418 - SDK drop: AController::Pawn - the authoritative pawn slot
    constexpr std::ptrdiff_t AcknowledgedPawn_Fallback              = 0x3D8;                                       // 0x3D8 - heuristic fallback only (now AController+0x3D8 is inside Character)  [lit/probed]
    constexpr std::ptrdiff_t Controller_Character                   = 0x400;                                       // Engine.Controller.Character = 0x400
    constexpr std::ptrdiff_t ControlRotation                        = 0x438;                                       // sdk/sdk.txt ArcOffsets::Controller::CONTROL_ROTATION = 0x438 (drop re-checked 2026-09-22) - SDK drop: AController::ControlRotation
    constexpr std::ptrdiff_t AController_PlayerState                = 0x3D0;                                       // sdk/sdk.txt ArcOffsets::Controller::PLAYER_STATE = 0x3D0 (drop re-checked 2026-09-22) - SDK drop: AController::PlayerState
    constexpr std::ptrdiff_t APlayerCameraManager                   = 0x4D0;                                       // 0x4D0 - non-UPROPERTY on PlayerController - live-pinned slot  [lit/probed]
    constexpr std::ptrdiff_t PlayerController_bIsLocalPlayerController = 0xD64;                                       // Engine.PlayerController.bIsLocalPlayerController = 0xD64 (byte 0xD64 mask 0x1) - APlayerController::bIsLocalPlayerController - the engine's own local-PC flag
    constexpr uint8_t        PlayerController_bIsLocalPlayerController_Mask = 0x1;                                         // 0x1 - bIsLocalPlayerController mask (declared bool mask=0x1 in the dump)  [lit/probed]
    constexpr std::ptrdiff_t APlayerState                           = 0x3E0;                                       // sdk/sdk.txt ArcOffsets::Pawn::PLAYER_STATE = 0x3E0 (drop re-checked 2026-09-22) - SDK drop: APawn::PlayerState
    constexpr std::ptrdiff_t PlayerNamePrivate                      = 0x458;                                       // Engine.PlayerState.PlayerNamePrivate = 0x458
    constexpr std::ptrdiff_t PlayerState_PawnPrivate                = 0x438;                                       // Engine.PlayerState.PawnPrivate = 0x438
    constexpr std::ptrdiff_t PlayerState_PlayerStatus               = 0x540;                                       // Angelscript.PioneerPlayerState.PlayerStatus = 0x540
    constexpr std::ptrdiff_t PioneerPlayerState_PioneerCharacter    = 0x558;                                       // Angelscript.PioneerPlayerState.PioneerCharacter = 0x558
    constexpr std::ptrdiff_t PioneerPlayerState_CurrentPawn         = 0x560;                                       // Angelscript.PioneerPlayerState.CurrentPawn = 0x560
    constexpr std::ptrdiff_t Pawn_Controller                        = 0x3F0;                                       // sdk/sdk.txt ArcOffsets::Pawn::CONTROLLER = 0x3F0 (drop re-checked 2026-09-22) - SDK drop: APawn::Controller
    constexpr std::ptrdiff_t PlayerNameOnPawn                       = 0x438;                                       // 0x438 - no longer a name slot on this build - heuristic only  [lit/probed]

    // -- PlayerCameraManager (TViewTarget @ 0x460, FMinimalViewInfo inside POV) 
    constexpr std::ptrdiff_t ViewTarget                             = 0x460;                                       // Engine.PlayerCameraManager.ViewTarget = 0x460 - TViewTarget (active)
    constexpr std::ptrdiff_t PendingViewTarget                      = 0xE10;                                       // Engine.PlayerCameraManager.PendingViewTarget = 0xE10 - TViewTarget (blend target)
    constexpr std::ptrdiff_t CameraPOV_Location                     = 0x470 + 0x10;                                // ViewTarget + 0x10 + 0x10 - TViewTarget::POV + FMinimalViewInfo::Location  [lit/probed]
    constexpr std::ptrdiff_t CameraPOV_Rotation                     = 0x470 + 0x38;                                // ViewTarget + 0x10 + 0x38 - TViewTarget::POV + FMinimalViewInfo::Rotation  [lit/probed]
    constexpr std::ptrdiff_t CameraPOV_FOV                          = 0x470 + 0x60;                                // ViewTarget + 0x10 + 0x60 - TViewTarget::POV + FMinimalViewInfo::FOV  [lit/probed]
    constexpr std::ptrdiff_t CameraLocation                         = CameraPOV_Location;                          // CameraPOV_Location  [lit/probed]
    constexpr std::ptrdiff_t CameraRotation                         = CameraPOV_Rotation;                          // CameraPOV_Rotation  [lit/probed]
    constexpr std::ptrdiff_t CameraFOV                              = CameraPOV_FOV;                               // CameraPOV_FOV  [lit/probed]
    constexpr std::ptrdiff_t PCOwner                                = 0x420;                                       // Engine.PlayerCameraManager.PCOwner = 0x420
    constexpr std::ptrdiff_t DefaultFOV                             = 0x430;                                       // Engine.PlayerCameraManager.DefaultFOV = 0x430
    constexpr std::ptrdiff_t LockedFOV                              = 0x43C;                                       // 0x43C - sdk.txt drop: APlayerCameraManager::LockedFOV (2026-09-22)  [lit/probed]

    // -- Pointer / global crypto (sdk.txt drop, 2026-09-22) ----------
    constexpr std::ptrdiff_t UWorldGlobalIntermediary               = 0x0;                                         // 0x0 - the GWorld global is [RVA] -> intermediary -> [+0x00] = UWorld (double deref)  [lit/probed]
    constexpr uint64_t       XmmXorVal                              = 0xA738DD8241D227C2;                          // 0xA738DD8241D227C2 - ArcOffsets::Crypto::XMM_XOR_VAL - decrypt_pointer_general XOR lane  [lit/probed]
    constexpr uint64_t       ObjectXorKeyRva                        = 0xD91F885;                                   // 0xD91F885 - ArcOffsets::ObjectXorKey::RVA - decrypt_object_ptr XOR key  [lit/probed]
    constexpr uint64_t       GetObjectIdSimdMaskRva                 = 0xAD2FC50;                                   // 0xAD2FC50 - ArcOffsets::GetObjectIdCrypto::SIMD_MASK_RVA  [lit/probed]
    constexpr uint64_t       GameInstanceStaticStageArrayRva        = 0x10F35650;                                  // sdk/sdk.txt GameInstanceStaticDecrypt::STAGE_ARRAY_RVA = 0x10F35650 - GameInstanceStaticDecrypt::STAGE_ARRAY_RVA - xmmword_150F35650 stage blocks
    constexpr uint64_t       GameInstanceStaticPshufbMaskRva        = 0xDDFC1D0;                                   // sdk/sdk.txt GameInstanceStaticDecrypt::PSHUFB_MASK_RVA = 0xDDFC1D0 - GameInstanceStaticDecrypt::PSHUFB_MASK_RVA - qword_14DDFC1D0
    constexpr uint64_t       GameInstanceStaticXorMask              = 0x291AED004FAE1FAC;                          // sdk/sdk.txt GameInstanceStaticDecrypt::XOR_MASK = 0x291AED004FAE1FAC - GameInstanceStaticDecrypt::XOR_MASK
    constexpr uint64_t       GameInstanceStaticAdd                  = 0x2A79E93E092D2538;                          // sdk/sdk.txt GameInstanceStaticDecrypt::ADD64 = 0x2A79E93E092D2538 - GameInstanceStaticDecrypt::ADD64
    constexpr uint32_t       GameInstanceStaticRot1                 = 0x38;                                        // sdk/sdk.txt GameInstanceStaticDecrypt::ROT64_1 = 0x38 - GameInstanceStaticDecrypt::ROT64_1
    constexpr uint32_t       GameInstanceStaticRot2                 = 0x21;                                        // sdk/sdk.txt GameInstanceStaticDecrypt::ROT64_2 = 0x21 - GameInstanceStaticDecrypt::ROT64_2
    constexpr std::ptrdiff_t GameInstanceStaticResultDeref          = 0x18;                                        // sdk/sdk.txt GameInstanceStaticDecrypt::RESULT_DEREF = 0x18 - GameInstanceStaticDecrypt::RESULT_DEREF - result = *(seed_ptr + 24)
    constexpr std::ptrdiff_t PlayerDecrypt_LocalPlayerOffset        = 0x4B0;                                       // 0x4B0 - APlayerController+0x4B0 - encrypted ULocalPlayer (APlayerController::GetLocalPlayer, sub_3680940)  [lit/probed]
    constexpr uint64_t       PlayerDecrypt_BlendXorMask             = 0x9A492C85DDF6F193;                          // sdk/sdk.txt PlayerDecrypt::BLEND_XOR_MASK = 0x9A492C85DDF6F193 - BLEND_XOR_MASK - the xmmword AND/ANDNOT pair collapses to one XOR
    constexpr uint32_t       PlayerDecrypt_LaneRot                  = 0xD;                                         // sdk/sdk.txt PlayerDecrypt::LANE_ROT = 0xD - LANE_ROT - ROL32 per 32-bit lane
    constexpr uint32_t       PlayerDecrypt_FinalRot                 = 0x27;                                        // sdk/sdk.txt PlayerDecrypt::FINAL_ROT = 0x27 - FINAL_ROT - ROL64 of the blended qword
    constexpr std::ptrdiff_t OuterDecrypt_SlotBaseOff               = 0x20;                                        // sdk/sdk.txt OuterDecrypt::SLOT_BASE_OFF = 0x20 - OuterDecrypt::SLOT_BASE_OFF - 4 encrypted UObject slots
    constexpr std::ptrdiff_t OuterDecrypt_SlotStride                = 0x20;                                        // sdk/sdk.txt OuterDecrypt::SLOT_STRIDE = 0x20 - OuterDecrypt::SLOT_STRIDE
    constexpr uint32_t       OuterDecrypt_HashPrime                 = 0x1000193;                                   // sdk/sdk.txt OuterDecrypt::HASH_PRIME = 0x1000193 - OuterDecrypt::HASH_PRIME (FNV 32)
    constexpr uint32_t       OuterDecrypt_HashAdd                   = 0x20193F54;                                  // sdk/sdk.txt OuterDecrypt::HASH_ADD = 0x20193F54 - OuterDecrypt::HASH_ADD
    constexpr uint32_t       OuterDecrypt_HashRot1                  = 0x19;                                        // sdk/sdk.txt OuterDecrypt::HASH_ROT_1 = 0x19 - OuterDecrypt::HASH_ROT_1
    constexpr uint32_t       OuterDecrypt_HashRot2                  = 0xF;                                         // sdk/sdk.txt OuterDecrypt::HASH_ROT_2 = 0xF - OuterDecrypt::HASH_ROT_2
    constexpr uint64_t       OuterDecrypt_XorMask                   = 0x9A492C85DDF6F193;                          // sdk/sdk.txt OuterDecrypt::XOR_MASK = 0x9A492C85DDF6F193 - OuterDecrypt::XOR_MASK
    constexpr uint32_t       OuterDecrypt_LaneRot                   = 0xD;                                         // sdk/sdk.txt OuterDecrypt::LANE_ROT = 0xD - OuterDecrypt::LANE_ROT - ROL32 per lane
    constexpr uint32_t       OuterDecrypt_FinalRot                  = 0x27;                                        // sdk/sdk.txt OuterDecrypt::FINAL_ROT = 0x27 - OuterDecrypt::FINAL_ROT - ROL64
    constexpr std::ptrdiff_t OuterDecrypt_HashSeedOff               = 0x10;                                        // 0x10 - literal in OuterDecrypt::decrypt_outer (sub_1439B00C0): hashes (obj + 0x10)  [lit/probed]
    constexpr uint32_t       OuterDecrypt_HashShr                   = 0x10;                                        // 0x10 - literal in OuterDecrypt::decrypt_outer: slot = ((h ^ (h >> 0x10)) & 3) ^ 2  [lit/probed]
    constexpr uint32_t       OuterDecrypt_SlotMask                  = 0x3;                                         // 0x3 - literal in OuterDecrypt::decrypt_outer: slot = ((h ^ (h >> 0x10)) & 3) ^ 2  [lit/probed]
    constexpr uint32_t       OuterDecrypt_SlotXor                   = 0x2;                                         // 0x2 - literal in OuterDecrypt::decrypt_outer: slot = ((h ^ (h >> 0x10)) & 3) ^ 2  [lit/probed]
    constexpr std::ptrdiff_t TebKeyOff                              = 0x1F8;                                       // sdk/sdk.txt TebDecrypt::TEB_KEY_OFF = 0x1F8 - TebDecrypt::TEB_KEY_OFF
    constexpr std::ptrdiff_t TebSelfPtrOff                          = 0x30;                                        // 0x30 - TebDecrypt::TEB_SELF_PTR_OFF  [lit/probed]
    constexpr uint32_t       TebWordRor                             = 0x1;                                         // sdk/sdk.txt TebDecrypt::WORD_ROR = 0x1 - TebDecrypt::WORD_ROR
    constexpr uint32_t       TebQwordRor                            = 0x3;                                         // sdk/sdk.txt TebDecrypt::QWORD_ROR = 0x3 - TebDecrypt::QWORD_ROR

    // -- GUObjectArray chunks manager (sdk.txt drop, 2026-09-22) -----
    constexpr uint64_t       ChunksManagerRva                       = 0x10C57060;                                  // sdk/sdk.txt FName::RVA_CHUNKMGR_GLOBAL = 0x10C57060 - RVA_CHUNKMGR_GLOBAL - encrypted chunks-manager pointer
    constexpr uint64_t       ChunksManagerXorRva                    = 0xD395260;                                   // sdk/sdk.txt FName::RVA_CHUNKMGR_XOR = 0xD395260 - RVA_CHUNKMGR_XOR
    constexpr uint64_t       ChunksManagerAddRva                    = 0xD395270;                                   // sdk/sdk.txt FName::RVA_CHUNKMGR_ADD = 0xD395270 - RVA_CHUNKMGR_ADD
    constexpr uint32_t       ChunksManagerRol32                     = 0x3;                                         // sdk/sdk.txt FName::CHUNKMGR_ROL32 = 0x3 - CHUNKMGR_ROL32
    constexpr std::ptrdiff_t ChunksManagerNumElementsOff            = 0x2C;                                        // sdk/sdk.txt FName::MGR_NUMELEMENTS_OFF = 0x2C - MGR_NUMELEMENTS_OFF
    constexpr uint32_t       ChunksManagerNumElementsXor            = 0x68D83F2C;                                  // sdk/sdk.txt FName::MGR_NUMELEMENTS_XOR = 0x68D83F2C - MGR_NUMELEMENTS_XOR
    constexpr std::ptrdiff_t ChunksManagerArrayOff                  = 0x20;                                        // sdk/sdk.txt FName::MGR_CHUNKARRAY_OFF = 0x20 - MGR_CHUNKARRAY_OFF
    constexpr uint64_t       ChunksManagerArrayXor                  = 0x464A80E000000000;                          // sdk/sdk.txt FName::MGR_CHUNKARRAY_XOR = 0x464A80E000000000 - MGR_CHUNKARRAY_XOR

    // -- FName pipeline v20260922 (sdk.txt drop constants) -----------
    constexpr uint64_t       FNameBlockXor                          = 0xF401C0BE961D3D9A;                          // sdk/sdk.txt FName::BLOCK_XOR = 0xF401C0BE961D3D9A - BLOCK_XOR
    constexpr uint32_t       FNameBlockRol64                        = 0x13;                                        // sdk/sdk.txt FName::BLOCK_ROL64 = 0x13 - BLOCK_ROL64
    constexpr uint32_t       FNameShardHashAdd                      = 0xD69AD929;                                  // sdk/sdk.txt FName::SHARD_HASH_ADD = 0xD69AD929 - SHARD_HASH_ADD
    constexpr std::ptrdiff_t FNameShardSeedOff                      = 0x40;                                        // sdk/sdk.txt FName::SHARD_HASH_SEED_OFF = 0x40 - SHARD_HASH_SEED_OFF
    constexpr std::ptrdiff_t FNameShardBlockBase                    = 0x50;                                        // sdk/sdk.txt FName::SHARD_BLOCK_BASE_OFF = 0x50 - SHARD_BLOCK_BASE_OFF
    constexpr std::ptrdiff_t FNameShardBlockStride                  = 0x20;                                        // sdk/sdk.txt FName::SHARD_BLOCK_STRIDE = 0x20 - SHARD_BLOCK_STRIDE
    constexpr uint32_t       FNameShardRolA                         = 0x11;                                        // sdk/sdk.txt FName::SHARD_ROL_A = 0x11 - SHARD_ROL_A
    constexpr uint32_t       FNameShardRolB                         = 0x1B;                                        // sdk/sdk.txt FName::SHARD_ROL_B = 0x1B - SHARD_ROL_B
    constexpr uint32_t       FNameShardFinalShr                     = 0x5;                                         // sdk/sdk.txt FName::SHARD_FINAL_SHR = 0x5 - SHARD_FINAL_SHR
    constexpr uint64_t       FNameFnvAdd                            = 0x6C5FD4827126D389;                          // sdk/sdk.txt FName::FNV_ADD = 0x6C5FD4827126D389 - FNV_ADD
    constexpr uint32_t       FNameFnvRol1                           = 0x28;                                        // sdk/sdk.txt FName::FNV_ROL1 = 0x28 - FNV_ROL1
    constexpr uint32_t       FNameFnvRol2                           = 0x32;                                        // sdk/sdk.txt FName::FNV_ROL2 = 0x32 - FNV_ROL2
    constexpr uint32_t       FNameKeystreamBaseIdx                  = 0xC;                                         // sdk/sdk.txt FName::KEYSTREAM_BASE_IDX = 0xC - KEYSTREAM_BASE_IDX
    constexpr uint32_t       FNameKeystreamCount                    = 0x100;                                       // sdk/sdk.txt FName::KEYSTREAM_COUNT = 0x100 - KEYSTREAM_COUNT (u16 words)
    constexpr uint32_t       FNameNarrowKeyShift                    = 0x3;                                         // sdk/sdk.txt FName::NARROW_KEY_SHIFT = 0x3 - NARROW_KEY_SHIFT
    constexpr std::ptrdiff_t FNameSlotBaseOff                       = 0x20;                                        // sdk/sdk.txt FName::SLOT_BASE_OFF = 0x20 - SLOT_BASE_OFF - UObject encrypted slot base
    constexpr std::ptrdiff_t FNameSlotStride                        = 0x20;                                        // sdk/sdk.txt FName::SLOT_STRIDE = 0x20 - SLOT_STRIDE
    constexpr uint32_t       FNameHeaderLenShift                    = 13;                                          // 13 - length = (hdr >> 13) | ((hdr >> 3) & 0x3F8) - v20260922 header layout  [lit/probed]

    // -- Bones v922 (sdk.txt drop, CL-1389382) -----------------------
    constexpr std::ptrdiff_t BoneV922SeedOffset                     = 0x7B0;                                       // 0x7B0 - BoneArrayDecrypt::SEED_OFFSET - 16-byte XMM seed  [lit/probed]
    constexpr std::ptrdiff_t BoneV922SelectorOffset                 = 0x848;                                       // 0x848 - BoneArrayDecrypt::SELECTOR_OFFSET - descriptor selector dword  [lit/probed]
    constexpr uint32_t       BoneV922SelectorShift                  = 15;                                          // 15 - SELECTOR_SHIFT  [lit/probed]
    constexpr uint32_t       BoneV922SelectorMask                   = 1;                                           // 1 - SELECTOR_MASK  [lit/probed]
    constexpr std::ptrdiff_t BoneV922DescriptorBase                 = 0x18;                                        // 0x18 - DESCRIPTOR_BASE - descriptor = Base + 0x18 + 0x10 * Selector  [lit/probed]
    constexpr std::ptrdiff_t BoneV922DescriptorStride               = 0x10;                                        // 0x10 - DESCRIPTOR_STRIDE  [lit/probed]
    constexpr uint64_t       BoneV922XorKeyLo                       = 0xC05F21012B46E100;                          // 0xC05F21012B46E100 - XOR_KEY_LO  [lit/probed]
    constexpr uint64_t       BoneV922AddKeyLo                       = 0x3FA0DEFFD4B91F00;                          // 0x3FA0DEFFD4B91F00 - ADD_KEY_LO  [lit/probed]
    constexpr uint32_t       BoneV922Rol32                          = 3;                                           // 3 - ROL32_AMOUNT (pslld 3 | psrld 29)  [lit/probed]
    constexpr std::ptrdiff_t BoneV922Stride                         = 0x60;                                        // 0x60 - BONE_STRIDE  [lit/probed]

    // -- Actor -------------------------------------------------------
    constexpr std::ptrdiff_t RootComponent                          = 0x240;                                       // Engine.Actor.RootComponent = 0x240
    constexpr std::ptrdiff_t ClassDefaultObject                     = 0x70;                                        // 0x70 - no dump source - int32 read on actor keys  [lit/probed]
    constexpr std::ptrdiff_t ClassDefaultObjectAlt                  = 0x78;                                        // 0x78 - no dump source  [lit/probed]
    constexpr std::ptrdiff_t ActorTypeId                            = 0xB0;                                        // 0xB0 - no dump source  [lit/probed]
    constexpr std::ptrdiff_t IsRenderedTime                         = 0x1F0;                                       // 0x1F0 - no dump source  [lit/probed]
    constexpr std::ptrdiff_t ActorID                                = 0x18;                                        // 0x18 - no dump source  [lit/probed]
    constexpr std::ptrdiff_t ActorOwner                             = 0x1D8;                                       // Engine.Actor.Owner = 0x1D8
    constexpr std::ptrdiff_t ActorInstigator                        = 0x220;                                       // Engine.Actor.Instigator = 0x220
    constexpr std::ptrdiff_t Actor_bHiddenByte                      = 0xD9;                                        // Engine.Actor.bHidden = 0xD9 (byte 0xD9 mask 0x1) - byte holding bHidden
    constexpr uint8_t        Actor_bHiddenMask                      = 0x1;                                         // Engine.Actor.bHidden mask
    constexpr std::ptrdiff_t Actor_FlagsDd                          = 0xDD;                                        // Engine.Actor.bActorEnableCollision = 0xDD (byte 0xDD mask 0x2) - byte holding bActorEnableCollision / bActorIsBeingDestroyed
    constexpr uint8_t        Actor_bActorEnableCollisionMask        = 0x2;                                         // Engine.Actor.bActorEnableCollision mask
    constexpr uint8_t        Actor_bActorIsBeingDestroyedMask       = 0x4;                                         // Engine.Actor.bActorIsBeingDestroyed mask
    constexpr std::ptrdiff_t ReplicatedMovement                     = 0x150;                                       // Engine.Actor.ReplicatedMovement = 0x150
    constexpr std::ptrdiff_t RepMov_LinearVelocity                  = 0x0;                                         // Engine.RepMovement.LinearVelocity = 0x0 - offset within FRepMovement
    constexpr std::ptrdiff_t Actor_InstanceComponents               = 0x398;                                       // Engine.Actor.InstanceComponents = 0x398

    // -- FTransform layout (CoreUObject.Transform from the dump) -----
    constexpr std::ptrdiff_t Transform_Rotation                     = 0x0;                                         // CoreUObject.Transform.Rotation = 0x0 - FTransform::Rotation (Quat, 0x20 bytes)
    constexpr std::ptrdiff_t Transform_Translation                  = 0x20;                                        // CoreUObject.Transform.Translation = 0x20 - FTransform::Translation (FVector3d) - the live world position
    constexpr std::ptrdiff_t Transform_Scale3D                      = 0x40;                                        // CoreUObject.Transform.Scale3D = 0x40 - FTransform::Scale3D (FVector3d)
    constexpr std::ptrdiff_t Transform_Size                         = 0x60;                                        // sizeof(CoreUObject.Transform) from dump - sizeof(FTransform) = Quat 0x20 + Translation 0x18 + pad 0x8 + Scale3D 0x18

    // -- SceneComponent ----------------------------------------------
    constexpr std::ptrdiff_t RelativeLocation                       = 0x268;                                       // Engine.SceneComponent.RelativeLocation = 0x268
    constexpr std::ptrdiff_t RelativeLocation_Alt                   = 0x2A8;                                       // 0x2A8 - ArcOffsets::SceneComponent::RELATIVE_LOCATION = 0x2A8 (conflicts with the dump's 0x268)  [lit/probed]
    constexpr std::ptrdiff_t RelativeRotation                       = 0x280;                                       // Engine.SceneComponent.RelativeRotation = 0x280
    constexpr std::ptrdiff_t ComponentVelocity                      = 0x2B0;                                       // Engine.SceneComponent.ComponentVelocity = 0x2B0
    constexpr std::ptrdiff_t ComponentToWorld                       = 0x310;                                       // 0x310 - v20260922 FTransform block; translation at +0x20 => 0x330  [live]
    constexpr std::ptrdiff_t ComponentToWorld_Alt                   = 0x2D0;                                       // 0x2D0 - previous build's slot, alternate candidate for the runtime probe  [lit/probed]
    constexpr std::ptrdiff_t ComponentToWorld_Rotation              = ComponentToWorld + Transform_Rotation;       // ComponentToWorld + Transform_Rotation - FTransform::Rotation (Quat) inside the block  [lit/probed]
    constexpr std::ptrdiff_t ComponentToWorld_Translation           = ComponentToWorld + Transform_Translation;    // ComponentToWorld + Transform_Translation - FTransform::Translation (FVector3d) inside the block  [lit/probed]
    constexpr std::ptrdiff_t ComponentToWorld_Scale3D               = ComponentToWorld + Transform_Scale3D;        // ComponentToWorld + Transform_Scale3D - FTransform::Scale3D (FVector3d) inside the block  [lit/probed]
    constexpr std::ptrdiff_t WorldLocation                          = ComponentToWorld_Translation;                // ComponentToWorld_Translation - the live world position (ComponentToWorld + 0x20, FVector3d LWC)  [lit/probed]
    constexpr std::ptrdiff_t Scene_bVisibleByte                     = 0x2C8;                                       // Engine.SceneComponent.bVisible = 0x2C8 (byte 0x2C8 mask 0x20)
    constexpr uint8_t        Scene_bVisibleMask                     = 0x20;                                        // Engine.SceneComponent.bVisible mask
    constexpr std::ptrdiff_t Scene_bHiddenInGameByte                = 0x2C9;                                       // Engine.SceneComponent.bHiddenInGame = 0x2C9 (byte 0x2C9 mask 0x10)
    constexpr uint8_t        Scene_bHiddenInGameMask                = 0x10;                                        // Engine.SceneComponent.bHiddenInGame mask
    constexpr std::ptrdiff_t AttachChildren                         = 0x1F8;                                       // Engine.SceneComponent.AttachChildren = 0x1F8

    // -- Primitive / skinned mesh ------------------------------------
    constexpr std::ptrdiff_t BoundsScale                            = 0x468;                                       // Engine.PrimitiveComponent.BoundsScale = 0x468
    constexpr std::ptrdiff_t LastRenderTime                         = 0x480;                                       // 0x480 - vis check user-provided 2026-09-23: PrimitiveComponent::LastRenderTime = 0x480 (plain float)  [live]
    constexpr std::ptrdiff_t LastRenderTimeOnScreen                 = 0x484;                                       // 0x484 - vis check user-provided 2026-09-23: LastRenderTimeOnScreen = 0x484 (plain float)  [live]
    constexpr std::ptrdiff_t LastSubmitTime                         = LastRenderTime;                              // LastRenderTime - alias kept for the LRTS raw fast-path (== LastRenderTime)  [lit/probed]
    constexpr std::ptrdiff_t VisibilityBasedAnimTickOption          = 0x9EC;                                       // Engine.SkinnedMeshComponent.VisibilityBasedAnimTickOption = 0x9EC
    constexpr std::ptrdiff_t bRecentlyRendered                      = 0x9F0;                                       // Engine.SkinnedMeshComponent.bRecentlyRendered = 0x9F0 (byte 0x9F0 mask 0x40) - byte holding bRecentlyRendered
    constexpr uint8_t        bRecentlyRenderedMask                  = 0x40;                                        // Engine.SkinnedMeshComponent.bRecentlyRendered mask

    // -- Bone decrypt slots (non-reflected - no dump source) ---------
    constexpr std::ptrdiff_t Encrypted                              = 0x7B0;                                       // 0x7B0 - bone pointer decrypt seed  [lit/probed]
    constexpr std::ptrdiff_t Encrypted_Legacy                       = 0x790;                                       // 0x790 - previous build's seed slot  [lit/probed]
    constexpr std::ptrdiff_t LodSelect                              = 0x7D0;                                       // 0x7D0 - LOD selector  [lit/probed]
    constexpr std::ptrdiff_t LodSelect_Legacy                       = 0x7D0;                                       // 0x7D0 - previous LOD slot  [lit/probed]

    // -- Mesh / character --------------------------------------------
    constexpr std::ptrdiff_t USkeletalMeshComponent_Alt             = 0x4A0;                                       // 0x4A0 - ArcOffsets::Actor::MESH = 0x4A0 (conflicts with the dump's 0x440)  [lit/probed]
    constexpr std::ptrdiff_t SkeletalMeshAsset_Alt                  = 0x740;                                       // 0x740 - ArcOffsets::SkeletalMeshComponent::SKELETAL_MESH = 0x740 (conflicts with the dump's 0x720)  [lit/probed]
    constexpr std::ptrdiff_t USkeletalMeshComponent                 = 0x440;                                       // Engine.Character.Mesh = 0x440 - ACharacter::Mesh
    constexpr std::ptrdiff_t SkeletalMeshAsset                      = 0x720;                                       // Engine.SkinnedMeshComponent.SkeletalMesh = 0x720
    constexpr std::ptrdiff_t bNoSkeletonUpdate                      = 0xCC0;                                       // Engine.SkeletalMeshComponent.bNoSkeletonUpdate = 0xCC0 (byte 0xCC0 mask 0x8)
    constexpr uint8_t        bNoSkeletonUpdateMask                  = 0x8;                                         // Engine.SkeletalMeshComponent.bNoSkeletonUpdate mask
    constexpr std::ptrdiff_t bForceRefpose                          = 0xCC1;                                       // Engine.SkeletalMeshComponent.bForceRefpose = 0xCC1 (byte 0xCC1 mask 0x1)
    constexpr uint8_t        bForceRefposeMask                      = 0x1;                                         // Engine.SkeletalMeshComponent.bForceRefpose mask
    constexpr std::ptrdiff_t CharacterMovement                      = 0x448;                                       // Engine.Character.CharacterMovement = 0x448
    constexpr std::ptrdiff_t Character_CapsuleComponent             = 0x450;                                       // Engine.Character.CapsuleComponent = 0x450
    constexpr std::ptrdiff_t CMC_LastUpdateLocation                 = 0x460;                                       // Engine.CharacterMovementComponent.LastUpdateLocation = 0x460
    constexpr std::ptrdiff_t StateInterpolator                      = 0x7A0;                                       // EmbarkCharacter.EmbarkCharacterBase.StateInterpolatorComponent = 0x7A0
    constexpr std::ptrdiff_t ReplicatedRootTransform                = 0x1F8;                                       // 0x1F8 - struct field on the interpolator state - no dump source  [lit/probed]
    constexpr std::ptrdiff_t Velocity                               = 0x1D0;                                       // Engine.MovementComponent.Velocity = 0x1D0
    constexpr std::ptrdiff_t PioneerCharacterMovement               = 0xB18;                                       // PioneerGameplay.PioneerCharacterBase.PioneerCharacterMovement = 0xB18
    constexpr std::ptrdiff_t HealthComponent                        = 0xDC0;                                       // Angelscript.PioneerPlayerCharacter.HealthComponent = 0xDC0
    constexpr std::ptrdiff_t InventoryComponent                     = 0xC80;                                       // Angelscript.PioneerPlayerCharacter.InventoryComponent = 0xC80
    constexpr std::ptrdiff_t EmbarkMesh                             = 0x7B8;                                       // EmbarkCharacter.EmbarkCharacterBase.EmbarkMesh = 0x7B8

    // -- Health ------------------------------------------------------
    constexpr std::ptrdiff_t HealthInfo                             = 0x550;                                       // 0x550 - derived block on PioneerPlayerState - no dump source  [lit/probed]
    constexpr std::ptrdiff_t PlayerState_Health                     = HealthInfo;                                  // HealthInfo  [lit/probed]
    constexpr std::ptrdiff_t PlayerState_MaxHealth                  = 0x558;                                       // 0x558 - derived - no dump source  [lit/probed]
    constexpr std::ptrdiff_t PlayerState_Armor                      = 0x560;                                       // 0x560 - derived - no dump source  [lit/probed]
    constexpr std::ptrdiff_t PlayerState_MaxArmor                   = 0x568;                                       // 0x568 - derived - no dump source  [lit/probed]
    constexpr std::ptrdiff_t Health                                 = 0x6D0;                                       // 0x6D0 - ArcOffsets::HealthComponent::CURRENT_HEALTH = 0x6D0 (live-verified; was the 0x700 FName shadow)  [live]
    constexpr std::ptrdiff_t HealthNameShadow                       = 0x700;                                       // Angelscript.HealthComponent.CachedHealth = 0x700 - FName on this build - value read is a name index, not a float
    constexpr std::ptrdiff_t MaxHealth                              = 0x348;                                       // 0x348 - ArcOffsets::HealthComponent::MAX_HEALTH = 0x348 (native, inside the dump's Pad_0340 hole)  [live]
    constexpr std::ptrdiff_t Shield                                 = 0x1C0;                                       // Angelscript.HealthComponent.Armor = 0x1C0 - FArmorSlot block
    constexpr std::ptrdiff_t ShieldMax                              = Shield + 0x10;                               // Shield + 0x10 - FArmorSlot::CurrentMaxArmor  [lit/probed]
    constexpr std::ptrdiff_t MaxDBNO                                = 0x380;                                       // Angelscript.HealthComponent.MaxDBNOHealth = 0x380 - FName
    constexpr std::ptrdiff_t TeamID                                 = 0x7F2;                                       // EmbarkCharacter.EmbarkCharacterBase.TeamId = 0x7F2

    // -- Inventory / weapons -----------------------------------------
    constexpr std::ptrdiff_t CurrentItemActors                      = 0x520;                                       // Angelscript.InventoryComponent.CurrentItemActors = 0x520
    constexpr std::ptrdiff_t LocalCurrentItemActors                 = 0x540;                                       // Angelscript.InventoryComponent.LocalCurrentItemActors = 0x540
    constexpr std::ptrdiff_t EquippedPrimaryItem                    = 0x588;                                       // Angelscript.InventoryComponent.EquippedArmor = 0x588 - reads the equipped armor slot
    constexpr std::ptrdiff_t WeaponClip                             = 0x490;                                       // Angelscript.BeamFirearmActor.ClipSize = 0x490
    constexpr std::ptrdiff_t WeaponQuality                          = 0x492;                                       // Angelscript.BeamFirearmActor.WeaponQuality = 0x492
    constexpr std::ptrdiff_t StowedWeaponSlot0                      = 0x3A0;                                       // Angelscript.InventoryComponent.StowedWeapon0 = 0x3A0
    constexpr std::ptrdiff_t StowedWeaponSlot1                      = 0x3E0;                                       // Angelscript.InventoryComponent.StowedWeapon1 = 0x3E0
    constexpr std::ptrdiff_t EquippedArmor                          = 0x588;                                       // Angelscript.InventoryComponent.EquippedArmor = 0x588

    // -- Loot / containers -------------------------------------------
    constexpr std::ptrdiff_t LootInteractionComponent               = 0xBB8;                                       // Angelscript.LootContainerSingle.LootInteractionComponent = 0xBB8
    constexpr std::ptrdiff_t LootContainer_ItemContainer            = 0xBD8;                                       // 0xBD8 - working runtime profile: LootContainer item-container field  [lit/probed]
    constexpr std::ptrdiff_t LootInteraction_Container              = LootInteractionComponent;                    // LootInteractionComponent - same slot  [lit/probed]
    constexpr std::ptrdiff_t SalvageContainer_ChosenMesh            = 0xCF0;                                       // Angelscript.SalvageContainerSingle.ChosenMesh = 0xCF0
    constexpr std::ptrdiff_t LootInteraction_Searched               = 0xBD8;                                       // 0xBD8 - working runtime profile: loot searched/state field  [lit/probed]
    constexpr std::ptrdiff_t SimpleLootActivity_LootInteraction     = 0x480;                                       // 0x480 - no dump source  [lit/probed]
    constexpr std::ptrdiff_t SimpleLootActivity_LootStateMachine    = 0x4A8;                                       // 0x4A8 - no dump source  [lit/probed]
    constexpr std::ptrdiff_t SimpleLootActivity_ItemContainer       = 0x498;                                       // 0x498 - no dump source  [lit/probed]
    constexpr std::ptrdiff_t SalvageContainer_MeshVariants          = 0xCB8;                                       // Angelscript.SalvageContainerSingle.MeshVariants = 0xCB8
    constexpr std::ptrdiff_t ItemDataAsset                          = 0x898;                                       // 0x898 - no dump source  [lit/probed]
    constexpr std::ptrdiff_t BP_PickupBase_SpawnItems               = 0x560;                                       // Angelscript.Pickup.SpawnItems = 0x560
    constexpr std::ptrdiff_t ItemContainer_OpenTime                 = 0x4E0;                                       // Angelscript.ItemContainerComponent.OpenTime = 0x4E0
    constexpr std::ptrdiff_t ConstructableItemContainer_OpenTime    = 0x470;                                       // Angelscript.ConstructableItemContainerComponent.OpenTime = 0x470
    constexpr std::ptrdiff_t ItemDataAsset_OverrideItemAssetId      = 0x120;                                       // 0x120 - no dump source  [lit/probed]
    constexpr std::ptrdiff_t ItemDataAsset_bOverrideItemAssetId     = 0x118;                                       // 0x118 - no dump source  [lit/probed]
    constexpr std::ptrdiff_t UIHoverData                            = 0x620;                                       // 0x620 - sdk.txt Pickup::UI_HOVER_DATA (FItemUIHoverData inline block; 0x550 was the pre-20260922 probe)  [lit/probed]
    constexpr std::ptrdiff_t UIHoverData_Pickup                     = UIHoverData;                                 // UIHoverData - same APickup field; compatibility alias for older call sites  [lit/probed]
    constexpr std::ptrdiff_t Pickup_RootCollider                    = 0x480;                                       // Angelscript.Pickup.RootCollider = 0x480 - the dump reflects it here and the CL drop agrees (was lit:0x470)
    constexpr std::ptrdiff_t Pickup_Interaction                     = 0x498;                                       // Angelscript.Pickup.Interaction = 0x498 - the dump reflects it here and the CL drop agrees (was lit:0x488)
    constexpr std::ptrdiff_t Pickup_DefaultPickupDataAsset          = 0x4A8;                                       // Angelscript.Pickup.DefaultPickupDataAsset = 0x4A8 - the dump reflects it here and the CL drop agrees (was lit:0x498)
    constexpr std::ptrdiff_t Pickup_ContainedItem_BB                = 0x4A0;                                       // 0x4A0 - no dump source  [lit/probed]
    constexpr std::ptrdiff_t BBItem_DataAssetIndex                  = 0x0;                                         // 0x0 - struct field  [lit/probed]
    constexpr std::ptrdiff_t BBItem_AmountValue                     = 0x4 + 0xC;                                   // 0x4 + 0xC - struct field  [lit/probed]
    constexpr std::ptrdiff_t ItemUIHoverData_DisplayName            = 0x0;                                         // 0x0 - sdk.txt ItemUIHoverData::DISPLAY_NAME - FText per-stack display name  [lit/probed]
    constexpr std::ptrdiff_t ItemUIHoverData_Amount                 = 0x18;                                        // 0x18 - sdk.txt ItemUIHoverData::AMOUNT - int32 stack amount  [lit/probed]
    constexpr std::ptrdiff_t ItemUIHoverData_MaxStack               = 0x1C;                                        // 0x1C - sdk.txt ItemUIHoverData::MAX_STACK - int32 max stack  [lit/probed]
    constexpr std::ptrdiff_t ItemUIHoverData_DataAsset              = 0x20;                                        // 0x20 - sdk.txt ItemUIHoverData::DATA_ASSET - UItemDataAsset*  [lit/probed]
    constexpr std::ptrdiff_t ItemUIHoverData_Size                   = 0x28;                                        // 0x28 - sizeof(FItemUIHoverData): FText 0x18 + amount + max stack + ptr  [lit/probed]
    constexpr std::ptrdiff_t Pickup_VisibleAmount                   = 0x4D0;                                       // 0x4D0 - sdk.txt Pickup::VISIBLE_AMOUNT (estimated) - visible stack amount  [lit/probed]
    constexpr std::ptrdiff_t Interaction_bIsActiveByte              = 0x137;                                       // 0x137 - no dump source  [lit/probed]
    constexpr uint8_t        Interaction_bIsActiveMask              = 0x8;                                         // 0x8  [lit/probed]
    constexpr std::ptrdiff_t Interaction_CurrentInteractionState    = 0x415;                                       // Angelscript.BaseInteractionComponent.CurrentInteractionState = 0x415

    // -- Constructables ----------------------------------------------
    constexpr std::ptrdiff_t bIsBreaked                             = 0x1230;                                      // Angelscript.PioneerConstructablePawn.bIsDestroyed = 0x1230 (byte 0x1230 mask 0x1)
    constexpr std::ptrdiff_t Constructable_EnemyTypeDataAsset       = 0x11C0;                                      // Angelscript.PioneerConstructablePawn.EnemyTypeDataAsset = 0x11C0
    constexpr std::ptrdiff_t Constructable_AITemplateData           = 0x11B0;                                      // Angelscript.PioneerConstructablePawn.AITemplateData = 0x11B0
    constexpr std::ptrdiff_t Constructable_bIsDestroyed             = 0x1230;                                      // Angelscript.PioneerConstructablePawn.bIsDestroyed = 0x1230 (byte 0x1230 mask 0x1)

    // -- Extraction / static mesh / misc -----------------------------
    constexpr std::ptrdiff_t ExtractionPoint_State                  = 0xC32;                                       // Angelscript.SalvageExtractionPointBase.State = 0xC32 - the drop's 0xBD2 is the pre-shift block; the dump reflects the state here
    constexpr std::ptrdiff_t ExtractionPoint_ExtractionInfo         = 0xBB8;                                       // Angelscript.SalvageExtractionPointBase.ExtractionInfo = 0xBB8 - FExtractionInfo { double startedTs; double time; } - timer struct
    constexpr std::ptrdiff_t ExtractionPoint_bIsEnabled             = 0xC30;                                       // Angelscript.SalvageExtractionPointBase.bIsEnabled = 0xC30 (byte 0xC30 mask 0x1)
    constexpr std::ptrdiff_t ExtractionPoint_StateChangeTimestamp   = 0xC38;                                       // Angelscript.SalvageExtractionPointBase.StateChangeTimestamp = 0xC38
    constexpr std::ptrdiff_t ExtractionPoint_TimeLeftAfterShutdown  = 0xC98;                                       // Angelscript.SalvageExtractionPoint.TimeLeftAfterShutdown = 0xC98 - config window (double seconds)
    constexpr std::ptrdiff_t ExtractionPoint_TimeLeftAfterStartup   = 0xCA0;                                       // Angelscript.SalvageExtractionPoint.TimeLeftAfterStartup = 0xCA0 - config window (double seconds)
    constexpr std::ptrdiff_t StaticMesh                             = 0x6D8;                                       // Engine.StaticMeshComponent.StaticMesh = 0x6D8
    constexpr std::ptrdiff_t StaticMesh_ExtendedBounds              = 0x368;                                       // Engine.StaticMesh.ExtendedBounds = 0x368 - FBoxSphereBounds on the asset
    constexpr std::ptrdiff_t StaticMeshLegacy                       = 0x718;                                       // 0x718 - previous build's slot  [lit/probed]
    constexpr std::ptrdiff_t Mesh_LastRenderTimeEnc                 = 0x4BC;                                       // 0x4BC - no dump source  [lit/probed]
    constexpr std::ptrdiff_t Mesh_LastRenderTimeOnScreenEnc         = 0x4C4;                                       // 0x4C4 - no dump source  [lit/probed]
    constexpr uint32_t       Mesh_LastRenderTimeKey                 = 0x5AB299E0;                                  // 0x5AB299E0 - XOR key  [lit/probed]
    constexpr uint32_t       Mesh_LastRenderTimeOnScreenKey         = 0xA83E5CBE;                                  // 0xA83E5CBE - XOR key  [lit/probed]
    constexpr std::ptrdiff_t UActorComponent_WorldPrivate           = 0x140;                                       // sdk/sdk.txt ArcOffsets::PrimitiveComponent::WORLD_PRIVATE = 0x140 - the drop found the UWorld ptr at +0x140 (live-verified 2026-08-20, was 0x148)
    constexpr std::ptrdiff_t UWorld_TimeSeconds                     = 0x240;                                       // sdk/sdk.txt ArcOffsets::UWorld::TIME_SECONDS = 0x240 - the drop re-verified it at +0x240 on 2026-09-09 (was 0x8B0); the dump pads the World tail

    // -- Replicated movement (Engine.RepMovement from the dump) ------
    constexpr std::ptrdiff_t RepMovement_Location                   = 0x30;                                        // Engine.RepMovement.Location = 0x30 - FRepMovement::Location - LWC double Vector, actor-relative to here
    constexpr std::ptrdiff_t RepMovement_Rotation                   = 0x48;                                        // Engine.RepMovement.Rotation = 0x48 - FRepMovement::Rotation
    constexpr std::ptrdiff_t RepMovement_AngularVelocity            = 0x18;                                        // Engine.RepMovement.AngularVelocity = 0x18 - FRepMovement::AngularVelocity
    constexpr std::ptrdiff_t RepMovement_ServerFrame                = 0x7C;                                        // Engine.RepMovement.ServerFrame = 0x7C - FRepMovement::ServerFrame
    constexpr std::ptrdiff_t RepMovement_bRepPhysicsByte            = 0x78;                                        // Engine.RepMovement.bRepPhysics = 0x78 (byte 0x78 mask 0x2) - byte holding FRepMovement::bRepPhysics
    constexpr uint8_t        RepMovement_bRepPhysicsMask            = 0x02;                                        // 0x02 - FRepMovement::bRepPhysics mask  [lit/probed]

    // -- Intel: loadout (InventoryComponent / stowed layout / weapon actors) 
    constexpr std::ptrdiff_t Inventory_Loadout                      = 0x2C0;                                       // sdk/sdk.txt ArcOffsets::InventoryComponent::LOADOUT = 0x2C0 (drop re-checked 2026-09-22) - FInventoryLoadout block start
    constexpr std::ptrdiff_t Inventory_Backpack                     = 0x4A0;                                       // sdk/sdk.txt ArcOffsets::InventoryComponent::BACKPACK = 0x4A0 (drop re-checked 2026-09-22) - backpack container slot (UItemContainer*)
    constexpr std::ptrdiff_t Inventory_Belt                         = 0x4A8;                                       // sdk/sdk.txt ArcOffsets::InventoryComponent::BELT = 0x4A8 (drop re-checked 2026-09-22) - belt container slot (UItemContainer*)
    constexpr std::ptrdiff_t Inventory_SafePouch                    = 0x4B0;                                       // sdk/sdk.txt ArcOffsets::InventoryComponent::SAFE_POUCH = 0x4B0 (drop re-checked 2026-09-22) - safe-pouch item slot (UItemBase*)
    constexpr std::ptrdiff_t StowedInfo_ItemDataAsset               = 0x18;                                        // sdk/sdk.txt ArcOffsets::StowedWeaponLayout::ITEM_DATA_ASSET = 0x18 - FStowedWeaponInfo::ItemDataAsset - DA_WeaponVisuals names the gun
    constexpr std::ptrdiff_t StowedInfo_Quality                     = 0x38;                                        // sdk/sdk.txt ArcOffsets::StowedWeaponLayout::WEAPON_QUALITY = 0x38 - FStowedWeaponInfo::WeaponQuality (int32 0-3 = I-IV)
    constexpr std::ptrdiff_t WeaponActor_ClipSize                   = 0x490;                                       // sdk/sdk.txt ArcOffsets::WeaponActor::CLIP_SIZE = 0x490 (drop re-checked 2026-09-22) - WeaponActor::ClipSize (uint16)
    constexpr std::ptrdiff_t WeaponActor_Quality                    = 0x492;                                       // sdk/sdk.txt ArcOffsets::WeaponActor::WEAPON_QUALITY = 0x492 (drop re-checked 2026-09-22) - WeaponActor::WeaponQuality (uint16)
    constexpr std::ptrdiff_t Inventory_StowedToolActor              = 0x420;                                       // sdk/sdk.txt ArcOffsets::InventoryComponent::STOWED_TOOL_ACTOR = 0x420 (drop re-checked 2026-09-22) - stowed tool slot (AStowedWeaponActor* - radar/knife/flashlight)
    constexpr std::ptrdiff_t StowedInfo_Size                        = 0x40;                                        // sdk/sdk.txt ArcOffsets::StowedWeaponLayout::STRUCT_SIZE = 0x40 - sizeof(FStowedWeaponInfo) stride pin
    constexpr std::ptrdiff_t ItemContainer_ItemLimit                = 0x4D8;                                       // Angelscript.ItemContainerComponent.ItemLimit = 0x4D8 - UItemContainer::ItemLimit - belt/backpack slot capacity
    constexpr std::ptrdiff_t ItemBase_Quality                       = 0x104;                                       // sdk/sdk.txt ArcOffsets::ItemBase::QUALITY_LEVEL = 0x104 - EItemRarity (0=common,1=rare,2=epic,3=legendary) on the item/CDO
    constexpr std::ptrdiff_t UClass_DefaultObjectSlot               = 0x158;                                       // CoreUObject.Class.ClassDefaultObject = 0x158 - UClass::ClassDefaultObject slot - rarity chain reads the CDO. The drop's ArcOffsets::UClass::DEFAULT_OBJECT 0x130 is the pre-shift CL-1341255 slot (0x130 is EClassCastFlags now) and the dump reflects the CDO here - same pattern as ExtractionPoint_State
    constexpr std::ptrdiff_t PickupDataAsset_ResolvedItemClass      = 0x150;                                       // sdk/sdk.txt ArcOffsets::PickupDataAsset::RESOLVED_ITEM_CLASS = 0x150 - pickup data asset -> resolved UItemBase class (rarity naming chain)
    constexpr std::ptrdiff_t Pickup_DefaultDataAsset                = 0x4A8;                                       // sdk/sdk.txt ArcOffsets::Pickup::DEFAULT_PICKUP_DATA_ASSET = 0x4A8 (drop re-checked 2026-09-22) - APickup::DefaultPickupDataAsset - the rarity chain's entry point

    // -- Intel: container state (socket parts / searched / dispenser) 
    constexpr std::ptrdiff_t LootContainer_SocketMesh               = 0xBB0;                                       // sdk/sdk.txt ArcOffsets::LootContainerSingle::SOCKET_LOOT_CONTAINER_MESH = 0xBB0 (drop re-checked 2026-09-22) - UStaticMeshComponent* carrying the socket loot parts
    constexpr std::ptrdiff_t LootInteract_OpenedByte                = 0x858;                                       // Angelscript.LootInteractionComponent.bHasBeenOpened = 0x858 (byte 0x858 mask 0x1) - bHasBeenOpened byte - the drop's BYTE_HAS_BEEN_OPENED 0x8D8 is the pre-shift slot; the dump reflects it here (same pattern as ExtractionPoint_State)
    constexpr uint8_t        LootInteract_OpenedMask                = 0x1;                                         // sdk/sdk.txt ArcOffsets::LootInteractionComponent::MASK_HAS_BEEN_OPENED = 0x1 - bHasBeenOpened bit mask
    constexpr std::ptrdiff_t LootInteract_AcquisitionMethod         = 0x80B;                                       // sdk/sdk.txt ArcOffsets::LootInteractionComponent::LOOT_ACQUISITION_METHOD = 0x80B (drop re-checked 2026-09-22) - LootAcquisitionMethod enum byte - values are not in the dump, so it only contributes a plausibility gate
    constexpr std::ptrdiff_t LootInteract_DispenserLocations        = 0x810;                                       // sdk/sdk.txt ArcOffsets::LootInteractionComponent::DISPENSER_LOCATIONS = 0x810 (drop re-checked 2026-09-22) - TArray<Vector> dispenser drop ports (dump-verified)
    constexpr std::ptrdiff_t LootInteract_PingIconOffset            = 0x860;                                       // sdk/sdk.txt ArcOffsets::LootInteractionComponent::LOOT_PING_ICON_OFFSET = 0x860 (drop re-checked 2026-09-22) - Vector loot-ping icon offset - block coherence gate (dump-verified)

    // -- Intel: DBNO / revive (FPlayerHealthInfo + interaction timers) 
    constexpr std::ptrdiff_t PlayerHealthInfoBase                   = 0x588;                                       // sdk/sdk.txt ArcOffsets::PlayerState::HEALTH_INFO_BASE = 0x588 - FPlayerHealthInfo inline block on PioneerPlayerState
    constexpr std::ptrdiff_t PHI_DBNOByte                           = 0x21;                                        // sdk/sdk.txt ArcOffsets::PlayerHealthInfo::B_IS_DBNO = 0x21 - byte in FPlayerHealthInfo holding bIsDBNO
    constexpr std::ptrdiff_t PHI_Health                             = 0x0;                                         // sdk/sdk.txt ArcOffsets::PlayerHealthInfo::HEALTH = 0x0 - double current health - block-anchor sanity gate
    constexpr std::ptrdiff_t PHI_MaxHealth                          = 0x8;                                         // sdk/sdk.txt ArcOffsets::PlayerHealthInfo::MAX_HEALTH = 0x8 - double max health - block-anchor sanity gate
    constexpr std::ptrdiff_t PHI_BrokenArmorByte                    = 0x20;                                        // sdk/sdk.txt ArcOffsets::PlayerHealthInfo::B_HAS_BROKEN_ARMOR = 0x20 - byte holding bHasBrokenArmor
    constexpr std::ptrdiff_t HC_MaxDBNOHealth                       = 0x380;                                       // sdk/sdk.txt ArcOffsets::HealthComponent::MAX_DBNO_HEALTH = 0x380 (drop re-checked 2026-09-22) - HealthComponent::MaxDBNOHealth (double)
    constexpr std::ptrdiff_t Interact_DBNOTimerFloats               = 0x428;                                       // sdk/sdk.txt ArcOffsets::BaseInteractionComponent::DBNO_TIMER_FLOATS = 0x428 - bleedout timer float pair
    constexpr std::ptrdiff_t Interact_DBNOTimerTicks                = 0x430;                                       // sdk/sdk.txt ArcOffsets::BaseInteractionComponent::DBNO_TIMER_TICKS = 0x430 - bleedout timer tick pair
    constexpr std::ptrdiff_t Interact_DefibTimerFloats              = 0x448;                                       // sdk/sdk.txt ArcOffsets::BaseInteractionComponent::DEFIB_TIMER_FLOATS = 0x448 - revive/defib timer float pair
    constexpr std::ptrdiff_t Interact_DefibTimerTicks               = 0x450;                                       // sdk/sdk.txt ArcOffsets::BaseInteractionComponent::DEFIB_TIMER_TICKS = 0x450 - revive/defib timer tick pair

    // -- Intel: look direction (PlayerCameraManager view clamps) -----
    constexpr std::ptrdiff_t PCM_ViewPitchMax                       = 0x2090;                                      // sdk/sdk.txt ArcOffsets::PlayerCameraManager::VIEW_PITCH_MAX = 0x2090 (drop re-checked 2026-09-22) - APlayerCameraManager::ViewPitchMax - rotation sanity clamp
    constexpr std::ptrdiff_t PCM_ViewPitchMin                       = 0x2098;                                      // sdk/sdk.txt ArcOffsets::PlayerCameraManager::VIEW_PITCH_MIN = 0x2098 (drop re-checked 2026-09-22) - APlayerCameraManager::ViewPitchMin
    constexpr std::ptrdiff_t PCM_ViewYawMax                         = 0x20A0;                                      // sdk/sdk.txt ArcOffsets::PlayerCameraManager::VIEW_YAW_MAX = 0x20A0 (drop re-checked 2026-09-22) - APlayerCameraManager::ViewYawMax
    constexpr std::ptrdiff_t PCM_ViewYawMin                         = 0x2094;                                      // sdk/sdk.txt ArcOffsets::PlayerCameraManager::VIEW_YAW_MIN = 0x2094 (drop re-checked 2026-09-22) - APlayerCameraManager::ViewYawMin

    // -- Intel: squads and identity (platform id + squad arrays) -----
    constexpr std::ptrdiff_t PS_PlatformIdComponent                 = 0x4B0;                                       // EmbarkGameplay.EmbarkPlayerStateBase.PlatformIdComponent = 0x4B0 - UEmbarkPlatformIdComponent* on AEmbarkPlayerStateBase
    constexpr std::ptrdiff_t PlatformId_Repl                        = 0x1B8;                                       // EmbarkGameplay.EmbarkPlatformIdComponent.PlatformId = 0x1B8 - FUniqueNetIdRepl (0x30 bytes)
    constexpr std::ptrdiff_t NetIdRepl_Object                       = 0x8;                                         // sdk/sdk.txt ArcOffsets::UniqueNetIdRepl::NET_ID_OBJECT = 0x8 - TVariant shared-ptr alternative object
    constexpr std::ptrdiff_t NetIdRepl_TypeIndex                    = 0x18;                                        // sdk/sdk.txt ArcOffsets::UniqueNetIdRepl::TYPE_INDEX = 0x18 - TVariant type index byte (0 = shared-ptr alternative)
    constexpr std::ptrdiff_t NetId_Payload                          = 0x18;                                        // sdk/sdk.txt ArcOffsets::UniqueNetId::PAYLOAD = 0x18 - FUniqueNetId payload - Steam CSteamID uint64
    constexpr std::ptrdiff_t PS_Squad                               = 0x488;                                       // EmbarkGameplay.EmbarkPlayerStateBase.Squad = 0x488 - UEmbarkSquad* - real squad membership
    constexpr std::ptrdiff_t EmbarkGS_SquadsArray                   = 0x4E8;                                       // sdk/sdk.txt ArcOffsets::EmbarkGameStateBase::SQUADS_ARRAY = 0x4E8 - TArray<UEmbarkSquad*>
    constexpr std::ptrdiff_t EmbarkGS_AllSquads                     = 0x6F0;                                       // sdk/sdk.txt ArcOffsets::EmbarkGameStateBase::ALL_SQUADS = 0x6F0 (drop re-checked 2026-09-22) - TArray<UEmbarkSquad*>
    constexpr std::ptrdiff_t EmbarkGS_MatchState                    = 0x4C0;                                       // sdk/sdk.txt ArcOffsets::EmbarkGameStateBase::MATCH_STATE = 0x4C0 - FName tag (InProgress/WaitingToStart/...)
    constexpr std::ptrdiff_t PS_PlayerNamePrivate2                  = 0x480;                                       // sdk/sdk.txt ArcOffsets::PlayerState::PLAYER_NAME_PRIVATE_2 = 0x480 - second name slot - fallback when PlayerNamePrivate reads empty
    constexpr std::ptrdiff_t PS_BotStateByte                        = 0x3CA;                                       // Engine.PlayerState.bIsABot = 0x3CA (byte 0x3CA mask 0x8) - packed bool byte - the drop's B_IS_A_BOT_BYTE 0x3DA is the pre-shift slot; the dump reflects the bools here (masks match bit for bit)
    constexpr uint8_t        PS_BotStateBotMask                     = 0x8;                                         // sdk/sdk.txt ArcOffsets::PlayerState::B_IS_A_BOT_MASK = 0x8 - bIsABot bit mask
    constexpr uint8_t        PS_BotStateSpectatorMask               = 0x2;                                         // sdk/sdk.txt ArcOffsets::PlayerState::B_IS_SPECTATOR_MASK = 0x2 - bIsSpectator bit mask
    constexpr std::ptrdiff_t PS_FinishedRoundByte                   = 0x5A8;                                       // Angelscript.PioneerPlayerState.bFinishedRound = 0x5A8 (byte 0x5A8 mask 0x1) - bFinishedRound bool byte - the drop's B_FINISHED_ROUND 0x5B8 is the pre-shift slot
    constexpr uint8_t        PS_FinishedRoundMask                   = 0x1;                                         // Angelscript.PioneerPlayerState.bFinishedRound mask - bFinishedRound bit mask
    constexpr std::ptrdiff_t PS_AchievementComponent                = 0x5B0;                                       // Angelscript.PioneerPlayerState.AchievementComponent = 0x5B0 - PioneerAchievementPlayerStateComponent* - the drop's ACHIEVEMENT_COMPONENT 0x5C0 is the pre-shift slot; doubles as the PioneerPlayerState block coherence anchor
    constexpr std::ptrdiff_t NetIdRepl_ReplBytesData                = 0x20;                                        // sdk/sdk.txt ArcOffsets::UniqueNetIdRepl::REPL_BYTES_DATA = 0x20 - TArray<uint8> ReplicationBytes.Data - FAccountId inline alternative
    constexpr std::ptrdiff_t NetIdRepl_ReplBytesCount               = 0x28;                                        // sdk/sdk.txt ArcOffsets::UniqueNetIdRepl::REPL_BYTES_COUNT = 0x28 - TArray<uint8> ReplicationBytes.Num

    // -- Intel: bot vision and alertness (AIPerception + AIStateService) 
    constexpr std::ptrdiff_t AIController_Perception                = 0x4A8;                                       // sdk/sdk.txt ArcOffsets::AIController::PERCEPTION_COMPONENT = 0x4A8 (drop re-checked 2026-09-22) - UAIPerceptionComponent* on the bot's AIController
    constexpr std::ptrdiff_t AIPerception_SensesConfig              = 0x1B8;                                       // sdk/sdk.txt ArcOffsets::AIPerceptionComponent::SENSES_CONFIG = 0x1B8 (drop re-checked 2026-09-22) - TArray<UAISenseConfig*>
    constexpr std::ptrdiff_t AISight_SightRadius                    = 0xC0;                                        // sdk/sdk.txt ArcOffsets::AISenseConfigSight::SIGHT_RADIUS = 0xC0 - UAISenseConfigSight::SightRadius (float, cm)
    constexpr std::ptrdiff_t AISight_LoseSightRadius                = 0xC4;                                        // sdk/sdk.txt ArcOffsets::AISenseConfigSight::LOSE_SIGHT_RADIUS = 0xC4 - LoseSightRadius (float, cm)
    constexpr std::ptrdiff_t AISight_PeripheralDeg                  = 0xC8;                                        // sdk/sdk.txt ArcOffsets::AISenseConfigSight::PERIPHERAL_VISION_DEG = 0xC8 - PeripheralVisionAngle (float, half-angle degrees)
    constexpr std::ptrdiff_t Constructable_AIStateService           = 0x12C0;                                      // sdk/sdk.txt ArcOffsets::PioneerConstructablePawn::AI_STATE_SERVICE = 0x12C0 - UPioneerConstructableAIStateService*
    constexpr std::ptrdiff_t AIState_Alertness                      = 0x1BC;                                       // sdk/sdk.txt ArcOffsets::AIStateService::ALERTNESS = 0x1BC - uint8 alertness (0=Idle .. 3=Combat)
    constexpr std::ptrdiff_t AIState_CombatPhase                    = 0x1C9;                                       // sdk/sdk.txt ArcOffsets::AIStateService::COMBAT_PHASE = 0x1C9 - uint8 combat phase (search/engage)
    constexpr std::ptrdiff_t AIState_SightRange                     = 0x1CC;                                       // sdk/sdk.txt ArcOffsets::AIStateService::SIGHT_RANGE = 0x1CC - float sight range (cm)
    constexpr std::ptrdiff_t AIState_SightHalfAngle                 = 0x1CA;                                       // sdk/sdk.txt ArcOffsets::AIStateService::SIGHT_HALF_ANGLE = 0x1CA - uint8 compressed degrees (half angle)

    // -- Intel: per-part damage (HealthService + style drivers) ------
    constexpr std::ptrdiff_t Constructable_HealthService            = 0x1280;                                      // sdk/sdk.txt ArcOffsets::PioneerConstructablePawn::HEALTH_SERVICE = 0x1280 - UConstructableHealthServiceComponent*
    constexpr std::ptrdiff_t PartHpArray                            = 0x280;                                       // sdk/sdk.txt ArcOffsets::HealthService::PART_HP_ARRAY = 0x280 - TArray<float> per-part hp fraction @ +0x280
    constexpr std::ptrdiff_t StyleDrivers                           = 0x610;                                       // sdk/sdk.txt ArcOffsets::ConstructableBase::ALL_STYLE_DRIVERS = 0x610 (drop re-checked 2026-09-22) - TArray style-driver components (per-part mesh style)
    constexpr std::ptrdiff_t Style_IsDestroyedByte                  = 0x7F9;                                       // sdk/sdk.txt ArcOffsets::ConstructableStaticMeshStyle::IS_DESTROYED = 0x7F9 - per-part destroyed flag byte
    constexpr std::ptrdiff_t Style_DestroyedReasonByte              = 0x7FA;                                       // sdk/sdk.txt ArcOffsets::ConstructableStaticMeshStyle::DESTROYED_REASON = 0x7FA - per-part destroyed reason byte
    constexpr std::ptrdiff_t Style_PartIdRange                      = 0x7E0;                                       // sdk/sdk.txt ArcOffsets::ConstructableStaticMeshStyle::PART_ID_RANGE = 0x7E0 - part id range in PART_HP_ARRAY

    // -- Intel: raid clock and match state (FStageInfo + PioneerGameState) 
    constexpr std::ptrdiff_t GameState_StageInfoRef                 = 0x938;                                       // sdk/sdk.txt ArcOffsets::GameState::STAGE_INFO = 0x938 (drop re-checked 2026-09-22) - FStageInfo inline block on PioneerGameState
    constexpr std::ptrdiff_t StageInfo_TimeLeftOff                  = 0x18;                                        // sdk/sdk.txt ArcOffsets::StageInfo::TIME_LEFT = 0x18 - FStageInfo::TimeLeft - raid clock seconds remaining
    constexpr std::ptrdiff_t StageInfo_GraceTimeOff                 = 0x20;                                        // sdk/sdk.txt ArcOffsets::StageInfo::GRACE_TIME = 0x20 - FStageInfo::GraceTime - post-raid grace seconds
    constexpr std::ptrdiff_t EmbarkGS_ElapsedTime                   = 0x4D0;                                       // sdk/sdk.txt ArcOffsets::EmbarkGameStateBase::ELAPSED_TIME = 0x4D0 - int32 seconds since match start

    // -- Intel: activity feed (interaction state + instigators) ------
    constexpr std::ptrdiff_t Interact_ActiveInstigator              = 0x658;                                       // sdk/sdk.txt ArcOffsets::BaseInteractionComponent::ACTIVE_INSTIGATOR = 0x658 - who is running the interaction right now
    constexpr std::ptrdiff_t Interact_DefaultInstigator             = 0x660;                                       // sdk/sdk.txt ArcOffsets::BaseInteractionComponent::DEFAULT_INSTIGATOR = 0x660 - default instigator slot

    // -- Intel: map radar (WorldPartitionMiniMap + level settings) ---
    constexpr std::ptrdiff_t MiniMap_UnitsPerPixel                  = 0x478;                                       // sdk/sdk.txt ArcOffsets::WorldPartitionMiniMap::WORLD_UNITS_PER_PIXEL = 0x478 (drop re-checked 2026-09-22) - world units per minimap pixel - authoritative radar scale
    constexpr std::ptrdiff_t MiniMap_WorldBounds                    = 0x3C0;                                       // sdk/sdk.txt ArcOffsets::WorldPartitionMiniMap::MINIMAP_WORLD_BOUNDS = 0x3C0 (drop re-checked 2026-09-22) - FBox world bounds
    constexpr std::ptrdiff_t MiniMap_TileSize                       = 0x488;                                       // sdk/sdk.txt ArcOffsets::WorldPartitionMiniMap::MINIMAP_TILE_SIZE = 0x488 (drop re-checked 2026-09-22) - minimap tile size
    constexpr std::ptrdiff_t MapLevel_HasUnderground                = 0x70;                                        // sdk/sdk.txt ArcOffsets::MapWidgetLevelSettings::HAS_UNDERGROUND = 0x70 - underground floor exists
    constexpr std::ptrdiff_t MapLevel_WorldSize                     = 0x50;                                        // sdk/sdk.txt ArcOffsets::MapWidgetLevelSettings::WORLD_SIZE = 0x50 - per-level map world size
    constexpr std::ptrdiff_t MapLevel_WorldPosition                 = 0x60;                                        // sdk/sdk.txt ArcOffsets::MapWidgetLevelSettings::WORLD_POSITION = 0x60 - per-level map world origin
    constexpr std::ptrdiff_t MapLevel_Stride                        = 0x78;                                        // sdk/sdk.txt ArcOffsets::MapWidgetLevelSettings::STRIDE = 0x78 - per-level settings element stride

    // -- SDK container layout (sdk/CppSDK/SDK/Basic.hpp + CoreUObject_classes.hpp) 
    constexpr std::ptrdiff_t UObject_ClassPrivate                   = 0x20;                                        // 0x20 - UObject::Class - CoreUObject_classes.hpp: class UObject, size 0xA0  [lit/probed]
    constexpr std::ptrdiff_t UObject_InternalIndex                  = 0x90;                                        // sdk/sdk.txt FName::UOBJECT_INTERNAL_IDX = 0x90 - UObject::Index - CoreUObject_classes.hpp
    constexpr std::ptrdiff_t UObject_NamePrivate                    = 0x98;                                        // 0x98 - UObject::Name - FName (u32 comparison index + u32 number)  [lit/probed]
    constexpr std::ptrdiff_t UObject_OuterPrivate                   = 0xA0;                                        // 0xA0 - UObject::Outer - CoreUObject_classes.hpp  [lit/probed]
    constexpr std::ptrdiff_t UObject_Size                           = 0xA0;                                        // sizeof(CoreUObject.Object) from dump - sizeof(UObject)
    constexpr std::ptrdiff_t FNamePool_Blocks                       = 0x40;                                        // 0x40 - FNamePool::Blocks[0x2000] - Basic.hpp (CurrentBlock 0x38, Cursor 0x3C)  [lit/probed]
    constexpr std::ptrdiff_t FNamePool_EntryStride                  = 0x02;                                        // 0x02 - FNamePool::FNameEntryStride - Basic.hpp  [lit/probed]
    constexpr std::ptrdiff_t FNamePool_BlockOffsetBits              = 0x10;                                        // 0x10 - FNamePool::FNameBlockOffsetBits - 0x10000 entries per block  [lit/probed]
    constexpr uint16_t       FNameEntry_WideBit                     = 0x1;                                         // sdk/sdk.txt FName::HDR_IS_WIDE_BIT = 0x1 - FNameEntryHeader::bIsWide - Basic.hpp
    constexpr uint16_t       FNameEntry_LenShift                    = 0x0006;                                      // 0x0006 - FNameEntryHeader::Len bit index - Basic.hpp  [lit/probed]
    constexpr uint16_t       FNameEntry_LenMask                     = 0x03FF;                                      // 0x03FF - FNameEntryHeader::Len (10 bits) - Basic.hpp  [lit/probed]
    constexpr std::ptrdiff_t FNameEntry_TextOffset                  = 0x02;                                        // 0x02 - FNameEntry::Name (FStringData) - char/wchar_t after the u16 header  [lit/probed]
    constexpr uint32_t       GObjects_ElementsPerChunk              = 0x10000;                                     // sdk/sdk.txt FName::ITEMS_PER_CHUNK = 0x10000 - TUObjectArray::ElementsPerChunk - Basic.hpp
    constexpr std::ptrdiff_t GObjects_ItemStride                    = 0x18;                                        // sdk/sdk.txt FName::FUOBJECTITEM_STRIDE = 0x18 - sizeof(FUObjectItem) - Basic.hpp
    constexpr std::ptrdiff_t GObjects_Item_Object                   = 0x8;                                         // sdk/sdk.txt FName::FUOBJECTITEM_OBJ_OFF = 0x8 - FUObjectItem::Object - Basic.hpp
    constexpr std::ptrdiff_t GObjects_NumElements                   = 0x0C;                                        // 0x0C - TUObjectArray::NumElements - Basic.hpp  [lit/probed]

}
